### ISSUE TITLE
ally.com filter blocking user-initiated notification expanded box

### ISSUE THREAD

**Issue by yourduskquibbles** [RedDragonWebDesign/block-everything#1]
When logged in to ally.com when the user clicks on the notification, the box window that would expand is hidden by the filter `secure.ally.com##.action-bar-content--notifications-container` I think this may be too aggressive but not sure what you were originally trying to hide with that filter.

With filter enabled after clicking notification bell:
![ally](https://user-images.githubusercontent.com/22258847/94812290-87b21380-03c4-11eb-995d-87028165a119.png)

With filter disabled after clicking notification bell:

![ally02](https://user-images.githubusercontent.com/22258847/94812433-b92adf00-03c4-11eb-9ce7-cb397e2dec6d.png)

**Comment by RedDragonWebDesign** [comment]
Thanks for using the list, and for reporting an issue. I'm glad the list is getting some use : )

It looks like that filter breaks the notification bell, so that's not good.

My original reason for adding it is that, for me, it pops open that notification bubble when I load my homepage, without me clicking on anything.

I removed the filter for now. If you can think of a good replacement filter, feel free to post!

**Comment by yourduskquibbles** [comment]
> If you can think of a good replacement filter, feel free to post!

I checked through you could maybe hide it from *only* the home page summary by targeting the selectors that are unique to only the summary page. e.g. something like this

`secure.ally.com##body[data-page-route=""] .reveal-panel-container.notifications-panel-container.is-revealed.dash-note, body[data-page-route=""] #notifications-link`

The `[data-page-route=""]` is empty when on the homepage but not when you navigate to other parts from what I can tell. Ideally it would still be expandable even on the homepage but not sure you can just force a page element to a certain state by faking a click e.g. force set on initial page load, `class="reveal-panel-container notifications-panel-container is-revealed dash-note"` to `class="reveal-panel-container notifications-panel-container dash-note"` (Notice the `is-revealed` class is removed when clicking the `x`).  Maybe could be done with setting a function to true? Seems overly complicated for what to me is such a minor annoyance though. 🤷‍♂️ Ultimately, it could just be a filter to keep in a personal blocklist vs a published list when there is no great option.
