### ISSUE TITLE
foxnews.com video player

### ISSUE THREAD

**Issue by yourduskquibbles** [RedDragonWebDesign/block-everything#10]
Hi again 😀I noticed what I think is probably unintentional hiding caused by the filter `foxnews.com##.featured-video` which is blocking video at the top of the article page that is related to the article. 

Not sure if that was intended or not with this filter but below is an example link where the video at top of page is related to the article and being hidden.

`https://www.foxnews.com/media/chaffetz-direct-evidence-joe-biden-hunters-business-deals`

**Comment by RedDragonWebDesign** [comment]
I was probably trying to target something else. Removed for now. Thanks for reporting.
