### ISSUE TITLE
hollywoodreporter.com header display misalignment

### ISSUE THREAD

**Issue by yourduskquibbles** [RedDragonWebDesign/block-everything#11]
Hi again :)

Found another cosmetic issue when testing my own filters. 

On `hollywoodreporter.com` the filter `hollywoodreporter.com##.js-Header-contents:style(position: absolute !important;)` is causing display wonkiness. 

Test link: `https://www.hollywoodreporter.com/news/music-news/britney-spears-calls-out-people-closest-to-her-who-failed-to-show-up-conservatorship-1234984063/` 

The header is "smooshed" together (there is probably a better technical term...) and aligns to the left side of the page when it should fill the full horizontal space and be aligned to the center of the page. The other two filters fix a scroll down/scroll up flashing issue on the header in the recommended filter updates below (which I've also [`added to Web Annoyances Ultralist`](https://github.com/yourduskquibbles/webannoyances/commit/bee1b53016da3b8529e4d810afcad91596e64c8b)).

```
! Disable block everything smooshed filter
hollywoodreporter.com#@#.js-Header-contents:style(position: absolute !important;)

! header filters to be design agnostic & remove flashing caused by scroll down/scroll up
hollywoodreporter.com##.js-Header-contents:style(position: relative !important; transform: none !important;)
hollywoodreporter.com##.is-sticky .js-hide-when-sticky:style(display: block !important;)
hollywoodreporter.com##.js-show-when-sticky

```

In future do you prefer if I just make a PR request with the fix and the rationale if I find small issues like this or a full issue report?

**Comment by RedDragonWebDesign** [comment]
Whatever is easier for you, my friend.

This list is meant to be run in tandem with Web Annoyances Ultralist. So I just went ahead and took out the problem filter you mentioned. Quick and easy fix. Hope that helps.
