### ISSUE TITLE
Didn't Block This

### ISSUE THREAD

**Issue by Ameno-Sagiri** [RedDragonWebDesign/block-everything#14]
Front page of Youtube. It doesn't block these banners.  Assuming maybe it was missed because it's a once a year insert that gets displayed during Black History month.
![2022-02-01-06-31-27_chrome](https://user-images.githubusercontent.com/5976053/151968747-e55de260-103e-4a86-a43a-46397ac3b61e.png)

**Comment by RedDragonWebDesign** [comment]
Blocking this would be a good fit for this list. But this ticket is 2 years old so I assume this banner is no longer showed. Closing for now.
