### ISSUE TITLE
How much should it block?

### ISSUE THREAD

**Issue by malwikt** [RedDragonWebDesign/block-everything#18]
I'm searching for filterlist that will block recommendations on websites.
For example here https://www.xda-developers.com/sega-ai-computer-1986-found/ it should hide 'Today's Best Deals', 'Trending Now', 'Recommended Articles'.
Here https://stackoverflow.com/questions/867877/ 'Featured on Meta' and 'Hot Network Questions'. 'Linked' and 'Related' should be left.

I don't like that from README: 
_Anything in news articles that is not normal article text. (e.g. related article links)_
If those links are really related then I think they are helpful. Of course links to unrelated articles should be blocked. And those are very popular on news sites.

So how much does that list is intended to block?

I would like to contribute if it's what I'm looking for.

Another question: could you maybe add some license or do you not plan to?

**Comment by chirag127** [comment]
I recommend you to use some reader instead. Or click on the reading mode in Microsoft edge. Or you can make your list by simply blocking each element you don't use by using the picker in the ublock origin.

**Comment by malwikt** [comment]
I already create my filters, but using other lists means less work. I like the examples from the readme, so I'm just interested what  exactly

> **everything** annoying

means.
I think examples I gave are in the same category as "Recommended Movies" or "Latest YouTube posts". But I'm not sure.

**Comment by chirag127** [comment]
> I already create my filters, but using other lists means less work. I like the examples from the readme, so I'm just interested what exactly
> 
> > **everything** annoying
> 
> means. I think examples I gave are in the same category as "Recommended Movies" or "Latest YouTube posts". But I'm not sure.

They are in same category. We don't block the related articles if they are integrated in the article and very related to the article.

**Comment by malwikt** [comment]
> We don't block the related articles if they are integrated in the article and very related to the article.

That's what I wanted. I should've been more precise. If related articles aren't about exactly or nearly exactly the same topic, they should be blocked.
I'm also interested in the license. I would prefer to contribute to something under free license. But I understand if @RedDragonWebDesign prefers to leave it without it.

**Comment by chirag127** [comment]
> > We don't block the related articles if they are integrated in the article and very related to the article.
> 
> That's what I wanted. I should've been more precise. If related articles aren't about exactly or nearly exactly the same topic, they should be blocked. I'm also interested in the license. I would prefer to contribute to something under free license. But I understand if @RedDragonWebDesign prefers to leave it without it.

For the license part I had the similar question. https://github.com/RedDragonWebDesign/block-everything/issues/6

It's not completely open licence licence seems like non Comercial gpl licence.

I also maintain my lists at https://github.com/chirag127/adblock/tree/main
The main list for the news site is https://github.com/chirag127/adblock/blob/main/chirag_annoyance_filters/AntiNewsSitesAnnoyances.txt

My anti news sites annoyance list removes everything like you want. But it only contain the news sites I use.

My license on https://github.com/chirag127/adblock/tree/main is completely open no limits. You are very welcome to contribute there.
