### ISSUE TITLE
facebook.com badfilter?

### ISSUE THREAD

**Issue by yourduskquibbles** [RedDragonWebDesign/block-everything#2]
Hi @RedDragonWebDesign I was looking through [`facebook events`](https://www.facebook.com/events) page and this filter `facebook.com##span:has-text(Coronavirus (COVID-19) Information):upward(18)` is causing the whole page to be hidden after loading for me. Maybe person specific but seems like a filter that could cause others issues as well.

**Comment by RedDragonWebDesign** [comment]
Commented them out for now. Thank you very much for the report.
