### ISSUE TITLE
linkedin.com

### ISSUE THREAD

**Issue by LanikSJ** [RedDragonWebDesign/block-everything#20]
The header on [LinkedIn](https://www.linkedin.com/mynetwork/grow/) (login required) hides a little too much.  The screenshots tells a better story.  You can see this on any page you browse to.
Broken:
![image](https://github.com/user-attachments/assets/1f5a793f-fba9-4362-866b-b55d9d712610)
Block Everything disabled:
![image](https://github.com/user-attachments/assets/c9b248da-761a-4a01-a041-e9c0b63c1b6b)
Disabling the list fixes the problem.  The problem filter seems to be: 
```
linkedin.com##.authentication-outlet:style(padding-top: 0 !important;)
```
Also disabling just that filter fixes the problem.
I'm using Chrome with latest uBO and tons of filter lists.  And yes I've tried to disable all of them one by one to isolate the problem.

**Comment by RedDragonWebDesign** [comment]
Is this on the homepage? It's working for me. Hmm.

<img width="903" alt="image" src="https://github.com/user-attachments/assets/14be0c70-0767-4c41-ac53-0fa10079da88">

Can you let me know which filter it is specifically? There's a setting in ubo that you can turn on that will let you open the logger and disable individual filters by clicking a #@# link. Filtering by cosmetic filters, then doing that one by one, can be a good way to debug filters.

**Comment by LanikSJ** [comment]
> Can you let me know which filter it is specifically?

This is the filter I found that causes the problem for me:
```
linkedin.com##.authentication-outlet:style(padding-top: 0 !important;)
```

**Comment by RedDragonWebDesign** [comment]
I can't reproduce it, so easiest to just delete the filter. Done in b0e2d46 :)

**Comment by LanikSJ** [comment]
Thank you 👍 😁 🙏
