### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by chirag127** [RedDragonWebDesign/block-everything#6]
Hey, I had a question. If I want to borrow some entries from your lists for a filter list on GitHub at https://github.com/chirag127/adblock/blob/main/personal then what is the formal procedure to do that?

**Comment by RedDragonWebDesign** [comment]
If it's just for personal use and you don't plan on sharing your list with many people, feel free to copy/paste them in, maybe with a comment and a backlink to my list. If you plan to share your list with many people, then I'd prefer to remain the central point and maintainer for these filters. Good luck with your list.

**Comment by chirag127** [comment]
> I'd prefer to remain the central point and maintainer for these filters.

can you please elaborate?
