### ISSUE TITLE
Linkedin.com bad filter

### ISSUE THREAD

**Issue by prxtiksingh** [RedDragonWebDesign/block-everything#8]
Hi @RedDragonWebDesign I was looking through Linkedin and this filter ```linkedin.com##a:has-text(Try Premium for free):upward(3)``` is causing the whole page to be hidden after loading for me. Maybe person specific but seems like a filter that could cause others issues as well

**Comment by RedDragonWebDesign** [comment]
Thanks for reporting. Yeah, `:upward()` is problematic. I'll go ahead and mass remove those filters for now. Feel free to respond with a list of new things I need to block, and I can try to write filters without using upward.
