### ISSUE TITLE
thedailybeast.com login & infinite scroll issue

### ISSUE THREAD

**Issue by yourduskquibbles** [RedDragonWebDesign/block-everything#9]
Hi @RedDragonWebDesign not sure if you want to fix this one or not, but I figured I'd report it since I figured this out while testing a fix for https://github.com/AdguardTeam/AdguardFilters/issues/80219 

The filter `||tinypass.com^$3p` is blocking the reported login modal from being shown as well. This may not be an issue you want to address since I think this filter also blocks the paywall so up to you if you want to try to improve the filter or not.

I personally use the following 3 filters in my personal list which I think doesn't cause the unintended breakage but achieves the same effect.

```
! tinypass breaks thedailybeast.com login modal & infinite scroll
@@||tinypass.com^$frame,script,xhr,domain=thedailybeast.com
||buy.tinypass.com/$subdocument
||cdn.tinypass.com^$script
```

**Comment by RedDragonWebDesign** [comment]
Hey YDQ. Great to hear from you. I hope you're doing well.

Sure, I'm happy to implement your fix. Done. Thanks for reporting.

**Comment by yourduskquibbles** [comment]
Thanks for greetings :) I am doing well, just had quite a busy time in my personal life so had to ignore Web Annoyances for a few months. now I am just slowly grinding through all of the outstanding bug reports now :)
